[simulation]
  name    = "bulkFlow"
  engine  = "srpic"
  runtime = 10.0

[grid]
  resolution = [640, 640]
  extent     = [[-64.0, 64.0], [-64.0, 64.0]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields    = [["PERIODIC"], ["PERIODIC"]]
    particles = [["PERIODIC"], ["PERIODIC"]]

[scales]
  larmor0    = 1.0
  skindepth0 = 1.0

[algorithms]
  current_filters = 4

  [algorithms.timestep]
    CFL = 0.5

[particles]
  ppc0 = 10.0

  [[particles.species]]
    label    = "e-_p"
    mass     = 1.0
    charge   = -1.0
    maxnpart = 3e8

  [[particles.species]]
    label    = "e+_p"
    mass     = 25.0
    charge   = 1.0
    maxnpart = 3e8

[setup]
  temperature = 10.0

[output]
  format        = "hdf5"
  interval_time = 12.0

  [output.fields]
    quantities = ["N_1","N_2","Rho_1","Rho_2","V1_1","V1_2", "J", "B", "E","T00_1","T00_2"]

  [output.particles]
    enable = false

  [output.spectra]
    enable = false

  [output.stats]
    enable = true

[checkpoint]
  interval = 10

[diagnostics]
  colored_stdout = false
